### ISSUE TITLE
Is anyone working on the Pretty Graphing Scripts project?

### ISSUE THREAD

**Issue by thisiselaine** [twood02/bounties#1]
Question is in the title. If not, I'd like to start a project. Thanks!

**Comment by twood02** [comment]
Not at the moment! Let me know if you have questions.

**Comment by twood02** [comment]
Closing this issue. The bounties are generally designed so that even if one person works on them, there is room for other to add/enhance. So feel free to suggest an improvement even after something gets "solved".
